### PR TITLE
feat: add rockspec

### PR DESCRIPTION
**Pull request by mrcjkb**
Created a new PR because #83 got closed and cannot be reopened. For some reason GitHub thinks it has over 250 commits.

###### Things done

- [x] Tested, as applicable:
  - [x] Manually
  - [ ] Added plenary specs
- [x] Updated [CHANGELOG.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by teto** [comment]
watching this again then :) I am thinking of updating several projects with your github action, is it ready yet ? what do you advise ?

**Comment by mrcjkb** [comment]
> watching this again then :) I am thinking of updating several projects with your github action, is it ready yet ? what do you advise ?

It works, but I haven't heard back from the `nvim-lua` maintainers. yet, and I haven't published it to the marketplace.

I'm also thinking of adding a `flake.nix` so I can use it in my nix CIs.

**Comment by teto** [comment]
> and I haven't published it to the marketplace.

does it prevent other repos from using it ?

> I haven't heard back from the nvim-lua maintainers.

looks like @tjdevries is sole member of the org ?! ( https://github.com/orgs/nvim-lua/people )

Even if were to be moved under the nvim-lua org, I suppose it should keep working even after moving it to the org so I wouldn't mind adding it to nvim-lspconfig for instance

**Comment by mrcjkb** [comment]
> does it prevent other repos from using it ?

I don't know. I guess it can't hurt to try it out.

> I suppose it should keep working even after moving it to the org

According to GitHub, all links would be redirected, so it should keep working.

**Comment by mrcjkb** [comment]
I have decided to maintain the GitHub action myself under the [nvim-neorocks](https://github.com/nvim-neorocks) organization.

This PR has been open for too long. Time to finally merge it.

**Comment by teto** [comment]
hourra \o/

**Comment by mrcjkb** [comment]
@all-contributors please add @teto for infra

**Pull request merged**
