### PR TITLE
feat!: version 2.x.x ftplugin rewrite

### PR DESCRIPTION
**Pull request by mrcjkb**
###### Description of changes
This is a major (breaking) rewrite of haskell-tools.nvim.

See also: https://github.com/mrcjkb/haskell-tools.nvim/discussions/227.

###### Things done

- [x] Tested, as applicable:
  - [x] Manually
  - [x] Added plenary specs
- [x] Updated [CHANGELOG.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mrcjkb** [comment]
TODO:

- [ ] Update `minimal.lua` + troubleshooting guide

**Comment by MangoIV** [comment]
```lua
local on_attach_def = function(client, bufnr)
    local function buf_set_option(...)
        vim.api.nvim_buf_set_option(bufnr, ...)
    end
    local buf_opts = { noremap = true, silent = true, buffer = bufnr }

    -- buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- show info
    vim.keymap.set("n", "K", vim.lsp.buf.hover, buf_opts)
    -- open diagnostic window
    vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, buf_opts)
    -- next error
    vim.keymap.set("n", "<space>n", vim.diagnostic.goto_next, buf_opts)
    -- prev error
    vim.keymap.set("n", "<space>p", vim.diagnostic.goto_prev, buf_opts)
    -- open code actions
    -- vim.keymap.set("n", "<space>c", 'CodeActionMenu', buf_opts)
    -- rename
    vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, buf_opts)
    -- goto references
    vim.keymap.set("n", "gr", vim.lsp.buf.references, buf_opts)
    -- goto definition
    vim.keymap.set("n", "gd", vim.lsp.buf.definition, buf_opts)
    -- format
    vim.keymap.set("n", "<space>rf", function()
        vim.lsp.buf.format({ async = true })
    end, buf_opts)

    vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, buf_opts)
    vim.keymap.set("n", "gD", vim.lsp.buf.declaration, buf_opts)
    vim.keymap.set("n", "gi", vim.lsp.buf.implementation, buf_opts)
    vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, buf_opts)
    vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, buf_opts)
    vim.keymap.set("n", "<space>wl", function()
        print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, buf_opts)
    vim.keymap.set("n", "<space>tl", lsplines.toggle, buf_opts)
end

local nvimlightbulb = require("nvim-lightbulb")
nvimlightbulb.setup({ autocmd = { enabled = true } })

-- Detect nvim-dap launch configurations
-- (requires nvim-dap and haskell-debug-adapter)

vim.g.haskell_tools = {
    hls = {
        on_attach = function(client, bufnr, ht)
            local opts = { noremap = true, silent = true, buffer = bufnr }
            ht.dap.discover_configurations(bufnr)
            -- haskell-language-server relies heavily on codeLenses,
            -- so auto-refresh (see advanced configuration) is enabled by default
            vim.keymap.set("n", "<space>a", vim.lsp.codelens.run, opts)
            -- Hoogle search for the type signature of the definition under the cursor
            vim.keymap.set("n", "<space>hs", ht.hoogle.hoogle_signature, opts)
            -- Evaluate all code snippets
            vim.keymap.set("n", "<space>ea", ht.lsp.buf_eval_all, opts)
            -- Toggle a GHCi repl for the current package
            vim.keymap.set("n", "<leader>rt", ht.repl.toggle, opts)
            -- Toggle a GHCi repl for the current buffer
            vim.keymap.set("n", "<leader>rb", function()
                ht.repl.toggle(vim.api.nvim_buf_get_name(0))
            end, opts)
            vim.keymap.set("n", "<leader>rq", ht.repl.quit, opts)

            on_attach_def(client, bufnr)
        end,
```

I have tried to adjust my config to the new version of `haskell-tools.nvim` and did this, but none of the keybindings work; may I ask what am I doing wrong? :3

**Comment by MangoIV** [comment]
god, I have to rewrite my entire config, this is an absolute mess...

**Comment by mrcjkb** [comment]
> god, I have to rewrite my entire config, this is an absolute mess...

Don't worry, you won't have to rewrite your entire config 😄 
Identifying stuff like this is why I posted #227 and am waiting before releasing.

Can you send me a link to your config so I can identify the problem?

**Comment by MangoIV** [comment]
> Don't worry, you won't have to rewrite your entire config smile

yeah this was independent of haskell.nvim, my config looks like frankensteins monster at this point heh

> Can you send me a link to your config so I can identify the problem?

https://git.sr.ht/~mangoiv/dotfiles/tree/07c75d8a75524e583e4ddf986481aaca3216fade/item/modules/home/devel/nvim/init.lua

**Comment by mrcjkb** [comment]
> > Don't worry, you won't have to rewrite your entire config smile
> 
> yeah this was independent of haskell.nvim, my config looks like frankensteins monster at this point heh
> 
> > Can you send me a link to your config so I can identify the problem?
> 
> https://git.sr.ht/~mangoiv/dotfiles/tree/07c75d8a75524e583e4ddf986481aaca3216fade/item/modules/home/devel/nvim/init.lua

It's nix, so I should be able to reproduce it. I'll give it a go after work 😅

**Comment by mrcjkb** [comment]
@MangoIV I had a look at your config and couldn't see anything wrong with it.

Maybe the call to `ht.dap.discover_configurations(bufnr)` is failing silently for some reason, and that's preventing the keymaps from being added?

Can you update the flake input and see if it works?
If not, I'll see if I can convert the home-manager module to a derivation and reproduce it this weekend.

**Comment by MangoIV** [comment]
Sure, will try and do that, thank you for investigating!

**Comment by MangoIV** [comment]
nah, that wasn't it... I will try to diff carefully and see where I messed up >D

**Comment by mrcjkb** [comment]
> nah, that wasn't it... I will try to diff carefully and see where I messed up >D

Hmm, here are some things you can try:

- What's the output of `:filetype`?
- What's the output of `:checkhealth haskell-tools`?
- Does it work if you open a Haskell file and run `:lua require('haskell-tools.internal').start_or_attach()`

**Comment by MangoIV** [comment]
nothing was getting called; I might have the solution and it might have been my stupid fault eh.

**Comment by mrcjkb** [comment]
> nothing is getting called eh.

That's very strange. I [use `vim.g.haskell_tools.hls.on_attach` to set keymaps](https://github.com/MrcJkb/nvim-config/blob/24916aad1af14e05db86af3f34183c0d19885edf/nvim/lua/plugin/haskell-tools.lua#L19) and it works fine for me.

Maybe somehow in you config, `require('haskell-tools')` is being called before you're setting `vim.g.haskell_tools`. Although I couldn't find any calls to it.
I'll investigate again after work. Could you please attach the ~/.config/nvim directory that home-manager generated for you?

**Comment by MangoIV** [comment]
it's just the same thing as on my git, except it first calls the `vimrc`

**Comment by MangoIV** [comment]
it's just the same thing as on my git, except it first calls the `vimrc`

**Comment by MangoIV** [comment]
indeed; removing the `vimrc` from my home-manager config solves it.

**Comment by MangoIV** [comment]
dirty-fix'd it.

**Comment by MangoIV** [comment]
image
!warning: extremely dirty fix eh

**Comment by mrcjkb** [comment]
> image !warning: extremely dirty fix eh
> 
> (This concatenates them in reverse order which somehow works)

I don't understand how your `vimrc` could interfere with haskell-tools, but okay, I guess :confu

**Comment by MangoIV** [comment]
I don’t know either tbh. Can’t imagine.

**Pull request merged**
