### PR TITLE
tests: add test with nixpkgs.wrapNeovim

### PR DESCRIPTION
**Pull request by mrcjkb**
###### Things done

- [x] Tested, as applicable:
  - [ ] Manually
  - [x] Added plenary specs
- [ ] Updated [CHANGELOG.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CHANGELOG.md) (if applicable).
- [x] Fits [CONTRIBUTING.md](https://github.com/MrcJkb/haskell-tools.nvim/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by teto** [comment]
I've submitted a bump of plenary https://github.com/NixOS/nixpkgs/pull/209765 . Now that it has tagged release we should default to that which I might do later but I just wanted to unblock you, let me know if using that branch unblocks you

**Comment by MrcJkb** [comment]
Thanks!
It looks like the outdated plenary package wasn't the issue after all.

The tests are still failing, because of https://github.com/NixOS/nixpkgs/issues/78033.
plenary.nvim (which I use to run the tests) uses `vim.v.progpath` to launch neovim.
So I will probably have to patch plenary to take an optional `nvim_cmd` argument.

**Comment by teto** [comment]
maybe plenary should restart `v:progpath` with `v:argv` in which case we could still see issues (as the nix wrapper may wrap some variables like PATH) but for the simple case it should work.

**Comment by MrcJkb** [comment]
> maybe plenary should restart `v:progpath` with `v:argv` in which case we could still see issues (as the nix wrapper may wrap some variables like PATH) but for the simple case it should work.

I think plenary needs to default to `v:progpath`, because it often needs to run things with a minimal config. Switching to `v:argv` could break a whole load of test suites.

**Pull request merged**
